version: '2'

networks:
  pubsub-network:
    external: true

services:

  rediscluster:
    image: rediscluster
    hostname: rediscluster
    networks:
        - pubsub-network
    expose:
        - "7000"
        - "7001"
        - "7002"
        - "7003"
        - "7004"
        - "7005"
        - "7006"
        - "7007"